// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package db

import (
	"database/sql"
	"time"
)

type Category struct {
	ID          string
	Name        string
	Description sql.NullString
	IsActive    bool
	CreatedAt   time.Time
}
